plugin:
    name: 'rezgui.leafletmap::lang.plugin.name'
    description: 'rezgui.leafletmap::lang.plugin.description'
    author: Yacine REZGUI
    icon: oc-icon-globe
    homepage: 'https://rezgui.net'
